package com.example.jhapcham.refund.domain;

public enum RefundStatus {
    ORDER_DELIVERED,
    REQUEST_CREATED,
    UNDER_REVIEW,
    MORE_EVIDENCE_REQUESTED,
    OFFER_MADE,
    SELLER_APPROVED,
    RETURN_PENDING,
    RETURN_SHIPPED,
    RETURN_RECEIVED,
    PRODUCT_INSPECTION,
    INSPECTION_COMPLETE,
    REFUND_PROCESSING,
    PENDING_ADMIN_VERIFICATION,
    REFUND_COMPLETED,
    SELLER_REJECTED,
    CUSTOMER_ACCEPTS,
    CLOSED,
    ADMIN_REVIEW,
    ADMIN_APPROVED_REFUND,
    ADMIN_REJECTED_REFUND,
    REPLACEMENT_PREPARING,
    REPLACEMENT_SHIPPED,
    EXCHANGE_COMPLETED
}
