package com.example.jhapcham.payment;

public enum PaymentErrorCode {
    PAYMENT_CANCELLED,
    @Deprecated
    ESEWA_LOGIN_FAILED,
    INSUFFICIENT_BALANCE,
    INVALID_SIGNATURE,
    PAYMENT_VERIFICATION_FAILED,
    PAYMENT_PENDING_VERIFICATION,
    DUPLICATE_TRANSACTION,
    PAYMENT_NOT_RETRYABLE,
    ORDER_NOT_FOUND,
    PAYMENT_NOT_FOUND,
    SERVER_ERROR
}
